apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: diagnosekode-api
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8300
  team: k9saksbehandling
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 5
    timeout: 1
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi
  ingresses:
    - "https://app-q1.adeo.no/diagnosekoder"
