name: Docker Image
on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '*.md'
    branches:
      - master

jobs:
  docker-deploy:
    name: Laste opp docker image
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v1
      - name: Sette opp Java
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Bygge JAR
        run: mvn clean package --settings ./.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Sette Docker- navn og tag
        env:
          DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/diagnosekode-api
        run: |
          echo "IMAGE=$DOCKER_IMAGE:$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "LATEST=$DOCKER_IMAGE:latest" >> $GITHUB_ENV
      - name: Bygge Docker image
        run: docker build . --pull --tag $IMAGE --tag $LATEST
      - name: Laste opp Docker image
        run: |
          echo "$GITHUB_TOKEN" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          docker push $LATEST
          docker push $IMAGE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy til testmiljø
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/dev-fss.yml
      - name: Deploy til prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: prod-fss
          RESOURCE: deploy/prod-fss.yml
