name: Snyk
on:
  push:
    branches: master
  workflow_dispatch:
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
          
      - uses: snyk/actions/setup@master

      - name: Create snyk-settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "github", "name": "github", "url": "https://maven.pkg.github.com/navikt/diagnosekode-api", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
          servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.READER_TOKEN }}" }]'
          output_file: snyk-settings.xml

      - name: Run Snyk monitor
        run: >
          snyk monitor
          --org=k9saksbehandling
          --configuration-attributes=usage:java-runtime
          --remote-repo-url=https://github.com/${{ github.repository }}.git
          -- -s snyk-settings.xml
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
